<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LRIN-QA-01" failures="1" tests="1" name="Default test" time="15.038" errors="0" timestamp="2021-04-09T13:38:47 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="14.405">
    <failure type="java.lang.AssertionError" message="expected [http://harjinder.login4website.com/CMS/word/wordpress/wp-admin/] but found [http://harjinder.login4website.com/CMS/word/wordpress/wp-login.php]">
      <![CDATA[java.lang.AssertionError: expected [http://harjinder.login4website.com/CMS/word/wordpress/wp-admin/] but found [http://harjinder.login4website.com/CMS/word/wordpress/wp-login.php]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at steps_definations.Hooks.func_loginUser(Hooks.java:168)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
